#ifndef AUDIO_TEST_PCM_H
#define AUDIO_TEST_PCM_H

#include <stdint.h>

#define AUDIO_TEST_PCM_SAMPLE_RATE_HZ  (48000U)
#define AUDIO_TEST_PCM_CHANNEL_COUNT   (2U)
#define AUDIO_TEST_PCM_FRAME_COUNT     (96000U)
#define AUDIO_TEST_PCM_SAMPLE_COUNT    (AUDIO_TEST_PCM_FRAME_COUNT * AUDIO_TEST_PCM_CHANNEL_COUNT)

extern const uint16_t g_audio_test_pcm[AUDIO_TEST_PCM_SAMPLE_COUNT];

#endif /* AUDIO_TEST_PCM_H */
