// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_ACCENT 0
#define UI_THEME_COLOR_INK 1
#define UI_THEME_COLOR_MUTED 2
#define UI_THEME_COLOR_WASH 3
#define UI_THEME_COLOR_GROUND 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Accent[1];
extern const ui_theme_variable_t _ui_theme_alpha_Accent[1];

extern const ui_theme_variable_t _ui_theme_color_Ink[1];
extern const ui_theme_variable_t _ui_theme_alpha_Ink[1];

extern const ui_theme_variable_t _ui_theme_color_Muted[1];
extern const ui_theme_variable_t _ui_theme_alpha_Muted[1];

extern const ui_theme_variable_t _ui_theme_color_Wash[1];
extern const ui_theme_variable_t _ui_theme_alpha_Wash[1];

extern const ui_theme_variable_t _ui_theme_color_Ground[1];
extern const ui_theme_variable_t _ui_theme_alpha_Ground[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
