// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Accent[1] = {0x00B0DE};
const ui_theme_variable_t _ui_theme_alpha_Accent[1] = {255};

const ui_theme_variable_t _ui_theme_color_Ink[1] = {0xF1F6FF};
const ui_theme_variable_t _ui_theme_alpha_Ink[1] = {255};

const ui_theme_variable_t _ui_theme_color_Muted[1] = {0x404040};
const ui_theme_variable_t _ui_theme_alpha_Muted[1] = {255};

const ui_theme_variable_t _ui_theme_color_Wash[1] = {0xE7E7E7};
const ui_theme_variable_t _ui_theme_alpha_Wash[1] = {40};

const ui_theme_variable_t _ui_theme_color_Ground[1] = {0x13223D};
const ui_theme_variable_t _ui_theme_alpha_Ground[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

