// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Blue1[1] = {0x00B0DE};
const ui_theme_variable_t _ui_theme_alpha_Blue1[1] = {255};

const ui_theme_variable_t _ui_theme_color_White1[1] = {0xF1F6FF};
const ui_theme_variable_t _ui_theme_alpha_White1[1] = {255};

const ui_theme_variable_t _ui_theme_color_Gray1[1] = {0x404040};
const ui_theme_variable_t _ui_theme_alpha_Gray1[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

