// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BLUE1 0
#define UI_THEME_COLOR_WHITE1 1
#define UI_THEME_COLOR_GRAY1 2
#define UI_THEME_COLOR_WHITEMASK1 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Blue1[1];
extern const ui_theme_variable_t _ui_theme_alpha_Blue1[1];

extern const ui_theme_variable_t _ui_theme_color_White1[1];
extern const ui_theme_variable_t _ui_theme_alpha_White1[1];

extern const ui_theme_variable_t _ui_theme_color_Gray1[1];
extern const ui_theme_variable_t _ui_theme_alpha_Gray1[1];

extern const ui_theme_variable_t _ui_theme_color_WhiteMask1[1];
extern const ui_theme_variable_t _ui_theme_alpha_WhiteMask1[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
