// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "../ui.h"

lv_obj_t * ui_Books = NULL;
// event funtions

// build funtions

void ui_Books_screen_init(void)
{
    ui_Books = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Books, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Books, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Books, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Books, &ui_img_wallpaper_indigo_mist_soft_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Books_screen_destroy(void)
{
    if(ui_Books) lv_obj_del(ui_Books);

    // NULL screen variables
    ui_Books = NULL;

}
