// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "../ui.h"

lv_obj_t * ui_BootReveal = NULL;
// event funtions
void ui_event_BootReveal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Service_GUI_Boot_RequestLock(e);
    }
}

// build funtions

void ui_BootReveal_screen_init(void)
{
    ui_BootReveal = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BootReveal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BootReveal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BootReveal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BootReveal, &ui_img_wallpaper_indigo_mist_soft_dark_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BootReveal, ui_event_BootReveal, LV_EVENT_ALL, NULL);

}

void ui_BootReveal_screen_destroy(void)
{
    if(ui_BootReveal) lv_obj_del(ui_BootReveal);

    // NULL screen variables
    ui_BootReveal = NULL;

}
