// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#ifndef UI_BOOTREVEAL_H
#define UI_BOOTREVEAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BootReveal
extern void ui_BootReveal_screen_init(void);
extern void ui_BootReveal_screen_destroy(void);
extern void ui_event_BootReveal(lv_event_t * e);
extern lv_obj_t * ui_BootReveal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

