// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "../ui.h"

lv_obj_t * ui_Boot = NULL;
lv_obj_t * ui_BootOrbitGroup = NULL;
lv_obj_t * ui_BootOrbitRing = NULL;
lv_obj_t * ui_BootOrbitLabel = NULL;
// event funtions
void ui_event_Boot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_BootReveal, LV_SCR_LOAD_ANIM_FADE_OUT, 400, 4000, &ui_BootReveal_screen_init);
    }
}

// build funtions

void ui_Boot_screen_init(void)
{
    ui_Boot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Boot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Boot, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_Boot_screen_destroy);
    lv_obj_set_style_bg_color(ui_Boot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Boot, &ui_img_wallpaper_indigo_mist_soft_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Boot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BootOrbitGroup = lv_obj_create(ui_Boot);
    lv_obj_remove_style_all(ui_BootOrbitGroup);
    lv_obj_set_width(ui_BootOrbitGroup, lv_pct(66));
    lv_obj_set_height(ui_BootOrbitGroup, lv_pct(66));
    lv_obj_set_x(ui_BootOrbitGroup, lv_pct(0));
    lv_obj_set_y(ui_BootOrbitGroup, lv_pct(-5));
    lv_obj_set_align(ui_BootOrbitGroup, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BootOrbitGroup, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BootOrbitGroup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BootOrbitGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BootOrbitRing = lv_arc_create(ui_BootOrbitGroup);
    lv_obj_set_width(ui_BootOrbitRing, lv_pct(33));
    lv_obj_set_height(ui_BootOrbitRing, lv_pct(30));
    lv_obj_set_x(ui_BootOrbitRing, 14);
    lv_obj_set_y(ui_BootOrbitRing, 4);
    lv_obj_set_align(ui_BootOrbitRing, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BootOrbitRing, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_BootOrbitRing, LV_DIR_TOP);
    lv_arc_set_value(ui_BootOrbitRing, 50);
    lv_arc_set_bg_angles(ui_BootOrbitRing, 0, 360);
    lv_obj_set_style_arc_color(ui_BootOrbitRing, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BootOrbitRing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BootOrbitRing, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_BootOrbitRing, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BootOrbitRing, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BootOrbitRing, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BootOrbitRing, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BootOrbitRing, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Skyblue);
    ui_object_set_themeable_style_property(ui_BootOrbitRing, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Skyblue);
    lv_obj_set_style_arc_width(ui_BootOrbitRing, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BootOrbitRing, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BootOrbitRing, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BootOrbitLabel = lv_label_create(ui_BootOrbitGroup);
    lv_obj_set_width(ui_BootOrbitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BootOrbitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BootOrbitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BootOrbitLabel, "LOADING");
    lv_obj_set_style_text_color(ui_BootOrbitLabel, lv_color_hex(0xF1F6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BootOrbitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Boot, ui_event_Boot, LV_EVENT_ALL, NULL);

}

void ui_Boot_screen_destroy(void)
{
    if(ui_Boot) lv_obj_del(ui_Boot);

    // NULL screen variables
    ui_Boot = NULL;
    ui_BootOrbitGroup = NULL;
    ui_BootOrbitRing = NULL;
    ui_BootOrbitLabel = NULL;

}
