// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#ifndef UI_BOOT_H
#define UI_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Boot
extern void ui_Boot_screen_init(void);
extern void ui_Boot_screen_destroy(void);
extern void ui_event_Boot(lv_event_t * e);
extern lv_obj_t * ui_Boot;
extern lv_obj_t * ui_BootOrbitGroup;
extern lv_obj_t * ui_BootOrbitRing;
extern lv_obj_t * ui_BootOrbitLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

