// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "../ui.h"

lv_obj_t * ui_Lock = NULL;
// event funtions

// build funtions

void ui_Lock_screen_init(void)
{
    ui_Lock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Lock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Lock, &ui_img_wallpaper_indigo_mist_soft_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Lock_screen_destroy(void)
{
    if(ui_Lock) lv_obj_del(ui_Lock);

    // NULL screen variables
    ui_Lock = NULL;

}
