// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_StatusBarContainer;
extern lv_obj_t * ui_StatusBarTimeContainer;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_StatusBarDateContainer;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_StatusBarBatteryContainer;
extern lv_obj_t * ui_StatusBarBatteryBarLabelContainer;
extern lv_obj_t * ui_StatusBarBatteryBar;
extern lv_obj_t * ui_StatusBarBatteryLabel;
extern lv_obj_t * ui_MainPageContainer;
extern lv_obj_t * ui_MusicPageContainer;
extern lv_obj_t * ui_MusicModeTabs;
extern lv_obj_t * ui_NowPlayingTab;
extern lv_obj_t * ui_QueueTab;
extern lv_obj_t * ui_SongPanel1;
extern lv_obj_t * ui_SongInfoContainer1;
extern lv_obj_t * ui_SongName1;
extern lv_obj_t * ui_SongCreator1;
extern lv_obj_t * ui_SongStatus1;
extern lv_obj_t * ui_LibraryTab;
extern lv_obj_t * ui_MusicPlayerControlContainer;
extern lv_obj_t * ui_MusicPlayingSlider;
extern lv_obj_t * ui_MusicPreviousButton;
extern lv_obj_t * ui_MusicPreviousIcon;
extern lv_obj_t * ui_MusicNextButton;
extern lv_obj_t * ui_MusicNextIcon;
extern lv_obj_t * ui_MusicPlayPauseButton;
extern lv_obj_t * ui_MusicPlayPauseIcon;
extern lv_obj_t * ui_BooksPageContainer;
extern lv_obj_t * ui_SettingsPageContainer;
extern lv_obj_t * ui_DotPanelContainer;
extern lv_obj_t * ui_DotSettings;
extern lv_obj_t * ui_DotMusic;
extern lv_obj_t * ui_DotBooks;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

