// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_StatusBarContainer = NULL;
lv_obj_t * ui_StatusBarTimeContainer = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_StatusBarDateContainer = NULL;
lv_obj_t * ui_DateLabel = NULL;
lv_obj_t * ui_StatusBarBatteryContainer = NULL;
lv_obj_t * ui_StatusBarBatteryBarLabelContainer = NULL;
lv_obj_t * ui_StatusBarBatteryBar = NULL;
lv_obj_t * ui_StatusBarBatteryLabel = NULL;
lv_obj_t * ui_MainPageContainer = NULL;
lv_obj_t * ui_MusicPageContainer = NULL;
lv_obj_t * ui_MusicModeTabs = NULL;
lv_obj_t * ui_NowPlayingTab = NULL;
lv_obj_t * ui_MusicPlayerControlContainer = NULL;
lv_obj_t * ui_MusicPlayingSlider = NULL;
lv_obj_t * ui_MusicPreviousButton = NULL;
lv_obj_t * ui_MusicPreviousIcon = NULL;
lv_obj_t * ui_MusicNextButton = NULL;
lv_obj_t * ui_MusicNextIcon = NULL;
lv_obj_t * ui_MusicPlayPauseButton = NULL;
lv_obj_t * ui_MusicPlayPauseIcon = NULL;
lv_obj_t * ui_QueueTab = NULL;
lv_obj_t * ui_SongPanel1 = NULL;
lv_obj_t * ui_SongInfoContainer1 = NULL;
lv_obj_t * ui_SongName1 = NULL;
lv_obj_t * ui_SongCreator1 = NULL;
lv_obj_t * ui_SongStatus1 = NULL;
lv_obj_t * ui_LibraryTab = NULL;
lv_obj_t * ui_BooksPageContainer = NULL;
lv_obj_t * ui_SettingsPageContainer = NULL;
lv_obj_t * ui_DotPanelContainer = NULL;
lv_obj_t * ui_DotSettings = NULL;
lv_obj_t * ui_DotMusic = NULL;
lv_obj_t * ui_DotBooks = NULL;
// event funtions

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Main, &ui_img_wallpaper_indigo_mist_soft_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBarContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_StatusBarContainer);
    lv_obj_set_width(ui_StatusBarContainer, lv_pct(100));
    lv_obj_set_height(ui_StatusBarContainer, lv_pct(5));
    lv_obj_set_align(ui_StatusBarContainer, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_StatusBarContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StatusBarContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarTimeContainer = lv_obj_create(ui_StatusBarContainer);
    lv_obj_remove_style_all(ui_StatusBarTimeContainer);
    lv_obj_set_width(ui_StatusBarTimeContainer, lv_pct(20));
    lv_obj_set_height(ui_StatusBarTimeContainer, lv_pct(90));
    lv_obj_set_align(ui_StatusBarTimeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarTimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLabel = lv_label_create(ui_StatusBarTimeContainer);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeLabel, "10:42");
    ui_object_set_themeable_style_property(ui_TimeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_TimeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Ink);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBarDateContainer = lv_obj_create(ui_StatusBarContainer);
    lv_obj_remove_style_all(ui_StatusBarDateContainer);
    lv_obj_set_width(ui_StatusBarDateContainer, lv_pct(50));
    lv_obj_set_height(ui_StatusBarDateContainer, lv_pct(90));
    lv_obj_set_align(ui_StatusBarDateContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarDateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateLabel = lv_label_create(ui_StatusBarDateContainer);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "AUG 24");
    ui_object_set_themeable_style_property(ui_DateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_DateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Ink);
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBarBatteryContainer = lv_obj_create(ui_StatusBarContainer);
    lv_obj_remove_style_all(ui_StatusBarBatteryContainer);
    lv_obj_set_width(ui_StatusBarBatteryContainer, lv_pct(20));
    lv_obj_set_height(ui_StatusBarBatteryContainer, lv_pct(90));
    lv_obj_set_x(ui_StatusBarBatteryContainer, lv_pct(0));
    lv_obj_set_y(ui_StatusBarBatteryContainer, lv_pct(4));
    lv_obj_set_align(ui_StatusBarBatteryContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarBatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_StatusBarBatteryContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatusBarBatteryContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatusBarBatteryContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatusBarBatteryContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBarBatteryBarLabelContainer = lv_obj_create(ui_StatusBarBatteryContainer);
    lv_obj_remove_style_all(ui_StatusBarBatteryBarLabelContainer);
    lv_obj_set_width(ui_StatusBarBatteryBarLabelContainer, lv_pct(50));
    lv_obj_set_height(ui_StatusBarBatteryBarLabelContainer, lv_pct(100));
    lv_obj_set_align(ui_StatusBarBatteryBarLabelContainer, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_StatusBarBatteryBarLabelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarBatteryBar = lv_bar_create(ui_StatusBarBatteryBarLabelContainer);
    lv_bar_set_value(ui_StatusBarBatteryBar, 84, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_StatusBarBatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_StatusBarBatteryBar, lv_pct(90));
    lv_obj_set_height(ui_StatusBarBatteryBar, lv_pct(90));
    lv_obj_set_align(ui_StatusBarBatteryBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarBatteryBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatusBarBatteryBar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatusBarBatteryBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarBatteryBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_StatusBarBatteryBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_StatusBarBatteryBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA,
                                           _ui_theme_alpha_Ink);
    lv_obj_set_style_outline_width(ui_StatusBarBatteryBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_StatusBarBatteryBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatusBarBatteryBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatusBarBatteryBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatusBarBatteryBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatusBarBatteryBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_StatusBarBatteryBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_StatusBarBatteryBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(ui_StatusBarBatteryBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Accent);

    ui_StatusBarBatteryLabel = lv_label_create(ui_StatusBarBatteryBarLabelContainer);
    lv_obj_set_width(ui_StatusBarBatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusBarBatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatusBarBatteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusBarBatteryLabel, "84");
    lv_obj_clear_flag(ui_StatusBarBatteryLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_StatusBarBatteryLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_StatusBarBatteryLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Ink);
    lv_obj_set_style_text_font(ui_StatusBarBatteryLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainPageContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_MainPageContainer);
    lv_obj_set_width(ui_MainPageContainer, lv_pct(100));
    lv_obj_set_height(ui_MainPageContainer, lv_pct(85));
    lv_obj_set_x(ui_MainPageContainer, lv_pct(0));
    lv_obj_set_y(ui_MainPageContainer, lv_pct(5));
    lv_obj_set_align(ui_MainPageContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_MainPageContainer,
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_MainPageContainer, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainPageContainer, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_MainPageContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPageContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MainPageContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainPageContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainPageContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainPageContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicPageContainer = lv_obj_create(ui_MainPageContainer);
    lv_obj_remove_style_all(ui_MusicPageContainer);
    lv_obj_set_width(ui_MusicPageContainer, lv_pct(100));
    lv_obj_set_height(ui_MusicPageContainer, lv_pct(100));
    lv_obj_set_y(ui_MusicPageContainer, 0);
    lv_obj_set_x(ui_MusicPageContainer, lv_pct(100));
    lv_obj_set_align(ui_MusicPageContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_MusicPageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_MusicPageContainer, LV_DIR_HOR);
    lv_obj_set_style_pad_left(ui_MusicPageContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MusicPageContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MusicPageContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MusicPageContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicModeTabs = lv_tabview_create(ui_MusicPageContainer, LV_DIR_TOP, 20);
    lv_obj_set_width(ui_MusicModeTabs, lv_pct(100));
    lv_obj_set_height(ui_MusicModeTabs, lv_pct(100));
    lv_obj_set_align(ui_MusicModeTabs, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_MusicModeTabs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicModeTabs, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicModeTabs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Ink);
    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_MusicModeTabs), 3,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_MusicModeTabs), lv_color_hex(0xE7E7E7),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_MusicModeTabs), 20,  LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Wash);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Wash);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_MusicModeTabs), LV_BORDER_SIDE_TOP,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_ITEMS | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_ITEMS | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Ink);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_MusicModeTabs), &lv_font_montserrat_12,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_MusicModeTabs), lv_color_hex(0xFFFFFF),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_MusicModeTabs), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Accent);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_MusicModeTabs), lv_color_hex(0xFFFFFF),
                              LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_MusicModeTabs), 0,  LV_PART_ITEMS | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_MusicModeTabs),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Accent);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_MusicModeTabs), 2,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_MusicModeTabs), LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_NowPlayingTab = lv_tabview_add_tab(ui_MusicModeTabs, "Playing");
    lv_obj_set_style_bg_color(ui_NowPlayingTab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NowPlayingTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NowPlayingTab, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_NowPlayingTab, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Ink);

    lv_obj_set_style_bg_color(ui_NowPlayingTab, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NowPlayingTab, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_MusicPlayerControlContainer = lv_obj_create(ui_NowPlayingTab);
    lv_obj_remove_style_all(ui_MusicPlayerControlContainer);
    lv_obj_set_width(ui_MusicPlayerControlContainer, lv_pct(90));
    lv_obj_set_height(ui_MusicPlayerControlContainer, lv_pct(28));
    lv_obj_set_align(ui_MusicPlayerControlContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_MusicPlayerControlContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_MusicPlayerControlContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MusicPlayerControlContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MusicPlayerControlContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MusicPlayerControlContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicPlayingSlider = lv_slider_create(ui_MusicPlayerControlContainer);
    lv_slider_set_value(ui_MusicPlayingSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MusicPlayingSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MusicPlayingSlider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_MusicPlayingSlider, lv_pct(90));
    lv_obj_set_height(ui_MusicPlayingSlider, lv_pct(7));
    lv_obj_set_x(ui_MusicPlayingSlider, lv_pct(0));
    lv_obj_set_y(ui_MusicPlayingSlider, lv_pct(5));
    lv_obj_set_align(ui_MusicPlayingSlider, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_MusicPlayingSlider, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicPlayingSlider, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicPlayingSlider, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MusicPlayingSlider, 1000, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MusicPlayingSlider, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(ui_MusicPlayingSlider, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Accent);

    lv_obj_set_style_radius(ui_MusicPlayingSlider, 1000, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicPlayingSlider, lv_color_hex(0x00B0DE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicPlayingSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MusicPlayingSlider, 1000, LV_PART_KNOB | LV_STATE_PRESSED);
    ui_object_set_themeable_style_property(ui_MusicPlayingSlider, LV_PART_KNOB | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(ui_MusicPlayingSlider, LV_PART_KNOB | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Accent);
    lv_obj_set_style_pad_left(ui_MusicPlayingSlider, 4, LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_pad_right(ui_MusicPlayingSlider, 4, LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_pad_top(ui_MusicPlayingSlider, 4, LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_pad_bottom(ui_MusicPlayingSlider, 4, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_MusicPreviousButton = lv_btn_create(ui_MusicPlayerControlContainer);
    lv_obj_set_width(ui_MusicPreviousButton, 35);
    lv_obj_set_height(ui_MusicPreviousButton, 35);
    lv_obj_set_x(ui_MusicPreviousButton, lv_pct(-30));
    lv_obj_set_y(ui_MusicPreviousButton, lv_pct(17));
    lv_obj_set_align(ui_MusicPreviousButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicPreviousButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MusicPreviousButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MusicPreviousButton, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicPreviousButton, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicPreviousButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_MusicPreviousButton, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicPreviousButton, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MusicPreviousButton, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_zoom(ui_MusicPreviousButton, 256, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MusicPreviousIcon = lv_label_create(ui_MusicPreviousButton);
    lv_obj_set_width(ui_MusicPreviousIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicPreviousIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_MusicPreviousIcon, 1);
    lv_obj_set_x(ui_MusicPreviousIcon, lv_pct(0));
    lv_obj_set_align(ui_MusicPreviousIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicPreviousIcon, "");
    ui_object_set_themeable_style_property(ui_MusicPreviousIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_MusicPreviousIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Ink);

    ui_MusicNextButton = lv_btn_create(ui_MusicPlayerControlContainer);
    lv_obj_set_width(ui_MusicNextButton, 35);
    lv_obj_set_height(ui_MusicNextButton, 35);
    lv_obj_set_x(ui_MusicNextButton, lv_pct(30));
    lv_obj_set_y(ui_MusicNextButton, lv_pct(17));
    lv_obj_set_align(ui_MusicNextButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicNextButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MusicNextButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MusicNextButton, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicNextButton, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicNextButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_MusicNextButton, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicNextButton, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MusicNextButton, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_zoom(ui_MusicNextButton, 256, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MusicNextIcon = lv_label_create(ui_MusicNextButton);
    lv_obj_set_width(ui_MusicNextIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicNextIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_MusicNextIcon, 1);
    lv_obj_set_x(ui_MusicNextIcon, lv_pct(0));
    lv_obj_set_align(ui_MusicNextIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicNextIcon, "");
    ui_object_set_themeable_style_property(ui_MusicNextIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_MusicNextIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Ink);

    ui_MusicPlayPauseButton = lv_btn_create(ui_MusicPlayerControlContainer);
    lv_obj_set_width(ui_MusicPlayPauseButton, 44);
    lv_obj_set_height(ui_MusicPlayPauseButton, 44);
    lv_obj_set_x(ui_MusicPlayPauseButton, lv_pct(0));
    lv_obj_set_y(ui_MusicPlayPauseButton, lv_pct(17));
    lv_obj_set_align(ui_MusicPlayPauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicPlayPauseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MusicPlayPauseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MusicPlayPauseButton, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicPlayPauseButton, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicPlayPauseButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_MusicPlayPauseButton, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicPlayPauseButton, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MusicPlayPauseButton, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_zoom(ui_MusicPlayPauseButton, 256, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MusicPlayPauseIcon = lv_label_create(ui_MusicPlayPauseButton);
    lv_obj_set_width(ui_MusicPlayPauseIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicPlayPauseIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicPlayPauseIcon, 1);
    lv_obj_set_y(ui_MusicPlayPauseIcon, 1);
    lv_obj_set_align(ui_MusicPlayPauseIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicPlayPauseIcon, "");
    ui_object_set_themeable_style_property(ui_MusicPlayPauseIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Ink);
    ui_object_set_themeable_style_property(ui_MusicPlayPauseIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Ink);

    ui_QueueTab = lv_tabview_add_tab(ui_MusicModeTabs, "Queue");
    lv_obj_set_flex_flow(ui_QueueTab, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_QueueTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_QueueTab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QueueTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_QueueTab, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_QueueTab, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_QueueTab, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_QueueTab, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_QueueTab, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_QueueTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_QueueTab, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QueueTab, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SongPanel1 = lv_obj_create(ui_QueueTab);
    lv_obj_set_width(ui_SongPanel1, lv_pct(100));
    lv_obj_set_height(ui_SongPanel1, lv_pct(17));
    lv_obj_set_align(ui_SongPanel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SongPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SongPanel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SongPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SongPanel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SongPanel1, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SongPanel1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SongPanel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(ui_SongPanel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Accent);
    lv_obj_set_style_border_width(ui_SongPanel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SongPanel1, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SongPanel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SongPanel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SongPanel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SongPanel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SongPanel1, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SongPanel1, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_SongPanel1, lv_color_hex(0xF1F6FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_SongPanel1, 80, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_SongPanel1, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_SongPanel1, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SongInfoContainer1 = lv_obj_create(ui_SongPanel1);
    lv_obj_remove_style_all(ui_SongInfoContainer1);
    lv_obj_set_width(ui_SongInfoContainer1, lv_pct(80));
    lv_obj_set_height(ui_SongInfoContainer1, lv_pct(100));
    lv_obj_set_align(ui_SongInfoContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SongInfoContainer1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SongInfoContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SongInfoContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SongName1 = lv_label_create(ui_SongInfoContainer1);
    lv_obj_set_width(ui_SongName1, lv_pct(100));
    lv_obj_set_height(ui_SongName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SongName1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SongName1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_SongName1, "SongLongggggggggggggName1");
    lv_obj_clear_flag(ui_SongName1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SongName1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(ui_SongName1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Accent);
    lv_obj_set_style_text_font(ui_SongName1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongCreator1 = lv_label_create(ui_SongInfoContainer1);
    lv_obj_set_width(ui_SongCreator1, lv_pct(100));
    lv_obj_set_height(ui_SongCreator1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SongCreator1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SongCreator1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SongCreator1, "SongCreator1");
    lv_obj_clear_flag(ui_SongCreator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_SongCreator1, lv_color_hex(0xF1F6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SongCreator1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SongCreator1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongStatus1 = lv_label_create(ui_SongPanel1);
    lv_obj_set_width(ui_SongStatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SongStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SongStatus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SongStatus1, "S");
    lv_obj_clear_flag(ui_SongStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SongStatus1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Accent);
    ui_object_set_themeable_style_property(ui_SongStatus1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Accent);
    lv_obj_set_style_text_font(ui_SongStatus1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LibraryTab = lv_tabview_add_tab(ui_MusicModeTabs, "Library");
    lv_obj_set_style_bg_color(ui_LibraryTab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LibraryTab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LibraryTab, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LibraryTab, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BooksPageContainer = lv_obj_create(ui_MainPageContainer);
    lv_obj_remove_style_all(ui_BooksPageContainer);
    lv_obj_set_width(ui_BooksPageContainer, lv_pct(100));
    lv_obj_set_height(ui_BooksPageContainer, lv_pct(100));
    lv_obj_set_y(ui_BooksPageContainer, 0);
    lv_obj_set_x(ui_BooksPageContainer, lv_pct(200));
    lv_obj_set_align(ui_BooksPageContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_BooksPageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_BooksPageContainer, LV_DIR_HOR);

    ui_SettingsPageContainer = lv_obj_create(ui_MainPageContainer);
    lv_obj_remove_style_all(ui_SettingsPageContainer);
    lv_obj_set_width(ui_SettingsPageContainer, lv_pct(100));
    lv_obj_set_height(ui_SettingsPageContainer, lv_pct(100));
    lv_obj_set_align(ui_SettingsPageContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_SettingsPageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SettingsPageContainer, LV_DIR_HOR);

    ui_DotPanelContainer = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_DotPanelContainer);
    lv_obj_set_width(ui_DotPanelContainer, lv_pct(100));
    lv_obj_set_height(ui_DotPanelContainer, lv_pct(10));
    lv_obj_set_align(ui_DotPanelContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_DotPanelContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DotPanelContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DotPanelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_DotPanelContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DotPanelContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DotSettings = lv_obj_create(ui_DotPanelContainer);
    lv_obj_set_width(ui_DotSettings, 5);
    lv_obj_set_height(ui_DotSettings, 5);
    lv_obj_set_x(ui_DotSettings, -41);
    lv_obj_set_y(ui_DotSettings, 137);
    lv_obj_set_align(ui_DotSettings, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DotSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DotSettings, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DotSettings, lv_color_hex(0xF1F6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DotSettings, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DotMusic = lv_obj_create(ui_DotPanelContainer);
    lv_obj_set_width(ui_DotMusic, 14);
    lv_obj_set_height(ui_DotMusic, 5);
    lv_obj_set_x(ui_DotMusic, -41);
    lv_obj_set_y(ui_DotMusic, 137);
    lv_obj_set_align(ui_DotMusic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DotMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DotMusic, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DotMusic, lv_color_hex(0xF1F6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DotMusic, 220, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DotBooks = lv_obj_create(ui_DotPanelContainer);
    lv_obj_set_width(ui_DotBooks, 5);
    lv_obj_set_height(ui_DotBooks, 5);
    lv_obj_set_x(ui_DotBooks, -41);
    lv_obj_set_y(ui_DotBooks, 137);
    lv_obj_set_align(ui_DotBooks, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DotBooks, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DotBooks, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DotBooks, lv_color_hex(0xF1F6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DotBooks, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_StatusBarContainer = NULL;
    ui_StatusBarTimeContainer = NULL;
    ui_TimeLabel = NULL;
    ui_StatusBarDateContainer = NULL;
    ui_DateLabel = NULL;
    ui_StatusBarBatteryContainer = NULL;
    ui_StatusBarBatteryBarLabelContainer = NULL;
    ui_StatusBarBatteryBar = NULL;
    ui_StatusBarBatteryLabel = NULL;
    ui_MainPageContainer = NULL;
    ui_MusicPageContainer = NULL;
    ui_MusicModeTabs = NULL;
    ui_NowPlayingTab = NULL;
    ui_MusicPlayerControlContainer = NULL;
    ui_MusicPlayingSlider = NULL;
    ui_MusicPreviousButton = NULL;
    ui_MusicPreviousIcon = NULL;
    ui_MusicNextButton = NULL;
    ui_MusicNextIcon = NULL;
    ui_MusicPlayPauseButton = NULL;
    ui_MusicPlayPauseIcon = NULL;
    ui_QueueTab = NULL;
    ui_SongPanel1 = NULL;
    ui_SongInfoContainer1 = NULL;
    ui_SongName1 = NULL;
    ui_SongCreator1 = NULL;
    ui_SongStatus1 = NULL;
    ui_LibraryTab = NULL;
    ui_BooksPageContainer = NULL;
    ui_SettingsPageContainer = NULL;
    ui_DotPanelContainer = NULL;
    ui_DotSettings = NULL;
    ui_DotMusic = NULL;
    ui_DotBooks = NULL;

}
