// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_StatusBarContainer;
extern lv_obj_t * ui_StatusBarTimeContainer;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_StatusBarDateContainer;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_StatusBarBatteryContainer;
extern lv_obj_t * ui_StatusBarBatteryBarLabelContainer;
extern lv_obj_t * ui_StatusBarBatteryBar;
extern lv_obj_t * ui_StatusBarBatteryLabel;
extern lv_obj_t * ui_MainPageContainer;
extern lv_obj_t * ui_MainPager;
extern lv_obj_t * ui_MusicPage;
extern lv_obj_t * ui_MusicModeTabs;
extern lv_obj_t * ui_NowPlayingTab;
extern lv_obj_t * ui_QueueTab;
extern lv_obj_t * ui_LibraryTab;
extern lv_obj_t * ui_BooksPage;
extern lv_obj_t * ui_SettingsPage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

