// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: mp3_gui

#include "../ui.h"

lv_obj_t * ui_Music = NULL;
// event funtions

// build funtions

void ui_Music_screen_init(void)
{
    ui_Music = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Music, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Music, &ui_img_wallpaper_indigo_mist_soft_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Music_screen_destroy(void)
{
    if(ui_Music) lv_obj_del(ui_Music);

    // NULL screen variables
    ui_Music = NULL;

}
